version: "3"
services: 
  web:
    build: .
    ports: 
      - "3001:3001"
    command: npm start 
    depends_on:
      - db
  db:
    image: postgres 
    restart: always
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=webaccess
      - POSTGRES_PASSWORD=popcorn
      - POSTGRES_DB=addidas
