version: "3"
services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile-dev
    ports: 
      - "80:3001"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres 
    restart: always
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=omarjandali
      - POSTGRES_PASSWORD=hackreactor25
      - POSTGRES_DB=addidas
